pymupdf.FileNotFoundError: no such file: 'DDAD-RHL-000021974_1_C_1_publication.pdf'
Traceback:
File "C:\Users\Raguvaran.Rajendran\OneDrive - Shell\Documents\PEFS_Validator\venv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Users\Raguvaran.Rajendran\OneDrive - Shell\Documents\PEFS_Validator\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Raguvaran.Rajendran\OneDrive - Shell\Documents\PEFS_Validator\app.py", line 39, in <module>
    output_bytes, summary = verify_drawings_memory(
                            ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Raguvaran.Rajendran\OneDrive - Shell\Documents\PEFS_Validator\core\verifier.py", line 67, in verify_drawings_memory
    df1 = extract_text_positions(drawing1_bytes)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Raguvaran.Rajendran\OneDrive - Shell\Documents\PEFS_Validator\core\extractor.py", line 6, in extract_text_positions
    doc = fitz.open(pdf_path)
          ^^^^^^^^^^^^^^^^^^^
File "C:\Users\Raguvaran.Rajendran\OneDrive - Shell\Documents\PEFS_Validator\venv\Lib\site-packages\pymupdf\__init__.py", line 2975, in __init__
    raise FileNotFoundError(f"no such file: '{filename}'")